- hosts: all
  become: yes
  tasks:

   - name: 'Disable swap for kubernetes'
     shell: swapoff -a


   - name: 'Update and upgrade'
     apt:
       # upgrade: yes
       update_cache: yes

   - name: 'Install docker. Uninstall old versions [1/5]'
     apt:
       pkg:
       - docker
       - docker-engine
       - docker.io
       - containerd
       - runc
       state: absent

   - name: 'Install docker. Install dependencies [2/5]'
     apt:
       pkg:
         - apt-transport-https
         - ca-certificates
         - curl
         - gnupg-agent
         - software-properties-common
       state: present

   - name: 'Install docker. Add Docker’s official GPG key [3/5]'
     apt_key:
       url: 'https://download.docker.com/linux/ubuntu/gpg'
       state: present
#   - name: 'Install docker. Set up the stable repository [4/5]'
#     shell: >-
#       add-apt-repository "deb [arch=amd64]
#       https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
   - name: 'Install docker. Set up the stable repository [4/5]'
     apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
      state: present
      update_cache: yes
   - name: 'Install docker. Install Docker Engine [5/5]'
     apt:
       update_cache: yes
       pkg:
         - docker-ce
         - docker-ce-cli
         - containerd.io
       state: present

   - name: 'Install docker. Post-installation [1/3]'
     getent:
       database: group

   - name: 'Install docker. Post-installation [2/3]'
     shell: groupadd docker
     when:
       - "'docker' not in ansible_facts.getent_group"

   - name: 'Install docker. Post-installation [3/3]'
     shell: usermod -aG docker $USER

   - name: Add remote "andrey" user to "docker" group
     remote_user: andrey
     user:
       name: "andrey"
       group: "docker"
       append: yes


   - name: add Kubernetes apt-key
     apt_key:
       url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
       state: present

   - name: add Kubernetes' APT repository
     apt_repository:
      repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: 'kubernetes'

   - name: install kubelet
     apt:
       name: kubelet
       state: present
       update_cache: true

   - name: install kubeadm
     apt:
       name: kubeadm
       state: present

- hosts: master
  become: yes
  gather_facts: no
  tasks:
   - name: install kubectl
     apt:
       name: kubectl
       state: present
     async: 60
     poll: 60

